default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: 1
  timeout: 5000

development:
  <<: *default
  database: poc_development

test:
  <<: *default
  database: poc_test

production:
  <<: *default
  database: poc_production

features:
  <<: *default
  database: poc_features
