github:
  organization: 'howtohireme'
  project:
    url: 'https://github.com/howtohireme/give-me-poc'
  default_team: 'bootcamp'
  api_token: <%= ENV['GITHUB_TOKEN'] %>
  oauth:
    client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    secret: <%= ENV['GITHUB_SECRET'] %>
    callback_domain: <%= ENV['GITHUB_CALLBACK_DOMAIN'] %>
slack:
  default_channel: 'bootcamp'
  ideas_channel: 'ideas'
  new_applications_channel: 'bootcamp-recruiting'
  bot_name: 'Notifications Bot'
notifications:
  email:
    default_from: 'givemepoc@gmail.com'
sheduler:
  time: '10:00'
facebook:
  page:
    url: 'https://www.facebook.com/givemepoc'
